# Generated by Django 5.1.3 on 2024-12-10 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(max_length=255)),
                ('court_type', models.CharField(choices=[('5', '5v5'), ('7', '7v7'), ('11', '11v11')], max_length=3)),
                ('availability', models.BooleanField()),
                ('create_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court.location')),
            ],
        ),
    ]
